action_selector: "epsilon_greedy"
runner: "parallel"
buffer_size: 5000
batch_size_run: 32
batch_size: 32
target_update_interval_or_tau: 500
learner: "q_learner"
mixer: "qmix"
agent: "rnn"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
gamma: 0.99
lr: 0.0005
hidden_dim: 64
t_max: 200000  # Total timesteps
name: "qmix_warehouse"
env_args:
  key: "WarehouseEnv-v0"
  time_limit: 200
